version: '3.8'

services:
  database:
    image: mongo:6
    container_name: insight_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - insight_db_data:/data/db

  backend:
    build: 
      context: ./sources/insight/backend
      dockerfile: Dockerfile
    container_name: insight_backend
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://database:27017
      - DATABASE_NAME=insight
      - SUPER_ADMIN_EMAILS=cuong.nguyen@aitc-jsc.com
    ports:
      - "3003:8001"
    depends_on:
      - database

  frontend:
    build:
      context: ./sources/insight/frontend
      dockerfile: Dockerfile
    container_name: insight_frontend
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - backend

volumes:
  insight_db_data:
